CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE user_role AS ENUM ('ADMIN', 'COACH', 'ATHLETE');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'PENDING', 'SUSPENDED', 'INACTIVE');
CREATE TYPE athlete_status AS ENUM ('ACTIVE', 'PAUSED', 'INJURED', 'INACTIVE');
CREATE TYPE coach_athlete_status AS ENUM ('ACTIVE', 'PAUSED', 'ENDED');
CREATE TYPE invite_status AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED');
CREATE TYPE athlete_program_type AS ENUM ('RUNNING', 'TRIATHLON', 'CYCLING', 'SWIMMING', 'GENERAL_FITNESS');
CREATE TYPE discipline_type AS ENUM ('RUN', 'BIKE', 'SWIM', 'STRENGTH', 'OTHER');
